#include "msp.h"                        // Device header
 
int main(){//SystemInit();
	
	EUSCI_A0->CTLW0 |= EUSCI_A_CTLW0_SWRST | 
										 EUSCI_A_CTLW0_SSEL__SMCLK ;//ESCOLHE O CLOCK
	EUSCI_A0->MCTLW |= EUSCI_A_MCTLW_OS16 |//OS16 = 1 
										 10 << EUSCI_A_MCTLW_BRF_OFS | // UCBRF ARMAZENA O INTEIRO
					           0xD6 << EUSCI_A_MCTLW_BRS_OFS; // UCBRS ARMAZENA UM VALOR SEGUNDO A TABELA DO REFERENCE 
	EUSCI_A0->BRW = 1;
	EUSCI_A0->CTLW0 &= ~EUSCI_A_CTLW0_SWRST;
	
	P1->SEL0 |= BIT2 | BIT3;//SELECIONA AF PARA O PINO 1.2
	P1->SEL1 &= ~BIT2 | BIT3;//SELECIONA AF PARA O PINO 1.3
	
	while(1)
	{
		while(!(EUSCI_A0->IFG & EUSCI_A_IFG_RXIFG));
		EUSCI_A0->IFG &= ~(EUSCI_A_IFG_RXIFG);
		EUSCI_A0->TXBUF = EUSCI_A0->RXBUF;
		while(!(EUSCI_A0->IFG & EUSCI_A_IFG_TXIFG));
		EUSCI_A0->IFG &= ~(EUSCI_A_IFG_TXIFG);	
	}
}
