#include "msp.h"                        // Device header

void TA1_0_IRQHandler(void);
volatile uint8_t unid = 0,dez = 0;

int main(){
	
//	EUSCI_A0->CTLW0 |= EUSCI_A_CTLW0_SWRST; 
//	EUSCI_A0->CTLW0 |= EUSCI_A_CTLW0_SSEL__SMCLK ;//ESCOLHE O CLOCK
//	EUSCI_A0->MCTLW |= EUSCI_A_MCTLW_OS16;//OS16 = 1
//	EUSCI_A0->MCTLW |= 10 << EUSCI_A_MCTLW_BRF_OFS | // UCBRF ARMAZENA O INTEIRO
//											0xD6 << EUSCI_A_MCTLW_BRS_OFS; // UCBRS ARMAZENA UM VALOR SEGUNDO A TABELA DO REFERENCE 
//	EUSCI_A0->BRW = 1;
//	EUSCI_A0->CTLW0 &= ~EUSCI_A_CTLW0_SWRST;
	
//	P1->SEL0 |= BIT2 | BIT3;//SELECIONA AF PARA O PINO 1.2
//	P1->SEL1 &= ~BIT2 | BIT3;//SELECIONA AF PARA O PINO 1.3
//	
	TIMER_A0->CTL |= TIMER_A_CTL_SSEL__SMCLK |//SELECIONA O CLOCK P/ O TIMER
	                 TIMER_A_CTL_ID_3;//DIVIDE O CLOCK POR 8
	TIMER_A0->EX0 |= TIMER_A_EX0_TAIDEX_5;//DIVIDE O CLOCK POR 6	
	TIMER_A0->CCR[0] = 500;
	TIMER_A0->CCR[1] = 250;
	TIMER_A0->CCR[2] = 250;
	TIMER_A0->CCTL[1] |= 6 << TIMER_A_CCTLN_OUTMOD_OFS | TIMER_A_CCTLN_CCIE;
	TIMER_A0->CCTL[2] |= 2 << TIMER_A_CCTLN_OUTMOD_OFS;
	
	P2->SEL0 |= BIT4|BIT5;
	P2->SEL1 &= ~(BIT4|BIT5);
	P2->DIR |= BIT4|BIT5;
	
	TIMER_A1->CTL |= TIMER_A_CTL_SSEL__SMCLK|
	                 TIMER_A_CTL_ID_3|//DIVIDE O CLOCK POR 8
	                 TIMER_A_CTL_IE;

	TIMER_A1->EX0 |= TIMER_A_EX0_TAIDEX_5;//DIVIDE O CLOCK POR 6
	TIMER_A1->CCTL[0] |= TIMER_A_CCTLN_CCIE;
	TIMER_A1->CCR[0] = 62500;
 
  NVIC_EnableIRQ(TA1_0_IRQn);
	
	TIMER_A0->CTL |= 1 << TIMER_A_CTL_MC_OFS;
	TIMER_A1->CTL |= 1 << TIMER_A_CTL_MC_OFS;
	
	P4->DIR |= BIT0|BIT1|BIT2|BIT3|BIT4|BIT5|BIT6;
	P4->OUT |= BIT0|BIT1|BIT2|BIT3|BIT4|BIT5|BIT6;
	
	P1->DIR |= BIT0; 
	P1->OUT &= ~BIT0;
	
	uint8_t dig[10] = {0xBF,0x86,0xDB,0xCF,0xE6,0xED,0xFD,0x87,0xFF,0xEF};	
	
	while(1)
	{	
		if(P2->IN & BIT4)
		{
		    P4->OUT = 0xFF;
		    P4->OUT &= ~(dig[dez]);
		}
		if(P2->IN & BIT5) 	
		{
		    P4->OUT = 0xFF;
		    P4->OUT &= ~(dig[unid]);
		}
	}
}

void TA1_0_IRQHandler(void)
{
	TIMER_A1->CCTL[0] &= ~TIMER_A_CCTLN_CCIFG;
	if(unid++ == 9)
	{
		unid = 0;
		if(dez++ == 9)
		{
			dez = 0;
		}
	}
}

//while(!(EUSCI_A0->IFG & EUSCI_A_IFG_RXIFG));
//		EUSCI_A0->IFG &= ~(EUSCI_A_IFG_RXIFG);
//		EUSCI_A0->TXBUF = EUSCI_A0->RXBUF;
